# Generated by Django 5.0.6 on 2024-06-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0005_jobapplymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasknamemodel',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tasknamemodel',
            name='status',
            field=models.CharField(default='On going', max_length=100, null=True),
        ),
    ]
